### ISSUE TITLE
選択中ハイライト色を、もう少し明るくしてほしい

### ISSUE THREAD

**Issue by yuru7** [choco14t/inkdrop-nord-syntax-theme#8]
Inkdrop の Nord テーマ、目に優しく、とても素敵です。
以下要望になりますが、お時間あるときに検討いただければ嬉しいです。

Inkdrop ver: 4.4.0
nord-syntax ver: 1.1.0

選択中のハイライトが暗く、品質 (コントラスト比？) があまり良くないディスプレイ (TN方式のディスプレイ等) で見ると、背景と選択中ハイライトが同化してしまい、選択中の範囲が識別しづらいです。

参考までに以下は、いくつかのエディタで Nord テーマを適用したキャプチャーです。 (`fuga` がハイライト部分)
せめて VSCode の Nord テーマ程度まで明度を上げると、ディスプレイに左右されず識別できると個人的には実感しています。

## Inkdrop (当プラグイン)
![image](https://user-images.githubusercontent.com/13458509/67995551-484be600-fc8e-11e9-9983-bca0a45f37cb.png)

## VSCode
![image](https://user-images.githubusercontent.com/13458509/67995514-19ce0b00-fc8e-11e9-9a2b-f6a93126ecfa.png)

## IntelliJ
![image](https://user-images.githubusercontent.com/13458509/67995665-fc4d7100-fc8e-11e9-8248-e6bb0818bb48.png)

**Comment by choco14t** [comment]
リクエストありがとうございます。
確認が遅くなってしまいすみません:(

あまり気になってなかったですが確かに選択部分がわかりづらいですね。
VSCodeの設定を確認したところ`#434C5ECC`と設定されていました。
（末尾のCCでopacity: 0.8が設定されています。）
https://github.com/arcticicestudio/nord-visual-studio-code/blob/74b3cac30f04cd2c8b5f15744dabb07dd64d6279/themes/nord-color-theme.json#L46-L47

以下が試しに同じスタイルを適用してみた画像です。
![image](https://user-images.githubusercontent.com/8362391/74562668-a76c0700-4fae-11ea-9447-ab63dae111e3.png)

またIntelliJでは`#4C566A`が設定されています。
https://github.com/arcticicestudio/nord-jetbrains/blob/1da0ddb87252d93da66944273e89365b2e6f745e/src/nord.theme.json#L29

個人的にこれは明るすぎな印象なので`#4C566ACC`を試してみました。
VSCodeのハイライトより少し明るめでテキストの視認性も悪くないのでこちらを適用しようと思っています。
![image](https://user-images.githubusercontent.com/8362391/74563697-af2cab00-4fb0-11ea-8d1a-ab37dfdd186d.png)

**Comment by choco14t** [comment]
v1.2.0を公開しました 🎉 
変更内容は以下から確認可能です。
* https://github.com/choco14t/inkdrop-nord-syntax-theme/compare/5907d22f5f62d65a1c933b8ef9b5a861924d2ed1...bcf6b5d11f6c1cb8139b46ad181b54475bdea33c
* [changelog](https://github.com/choco14t/inkdrop-nord-syntax-theme/blob/master/CHANGELOG.md)

**Comment by yuru7** [comment]
ありがとうございます！試してみます 🥰
