### ISSUE TITLE
Support highlighting active line

### ISSUE THREAD

**Issue by craftzdog** [choco14t/inkdrop-nord-syntax-theme#9]
Hi, the Inkdrop developer here.

As you may know, v4.6.1 supported highlighting the current line: https://forum.inkdrop.app/t/highlight-line/1823/6

It requires your syntax theme to be updated as Otawara-san did above, because currently it is hard to see:

<img width="513" alt="Screen Shot 2020-03-24 at 16 02 38" src="https://user-images.githubusercontent.com/1332805/77397539-28f25880-6de9-11ea-991e-c4e321380134.png">

Since I really love your syntax theme, could you find a time to work on it please?
Thanks a lot!

**Comment by choco14t** [comment]
Hi, thanks for reporting :)

Refer to the link, I released the fixed version(v1.4.0) now.
Please update and check it.

**Comment by craftzdog** [comment]
Perfect!!
